name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          workdir: .
          python-version: '3.10'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: secret-room-apk
          path: bin/*.apk
